name: Combine Remote Playlists

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  combine-playlists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run combine script
      run: python combine_remote_playlists_with_epg.py

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add combined_playlist.m3u
          git commit -m "Auto-update combined playlist"
          git push
        else
          echo "No changes to commit"
        fi
@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Run script to combine playlists
      run: |
        python combine_remote_playlists_with_epg.py

    - name: Commit and push changes
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git add combined_playlist.m3u
        git commit -m "Update combined playlist" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
